name: Build & Deploy Image to Dev

on:
  push:
    branches: [main]

env:
  IMAGE: ghcr.io/integration-project-2026-groep-2/mcp-master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          docker build -t ${{ env.IMAGE }}:sha-${SHORT_SHA} .
          docker tag ${{ env.IMAGE }}:sha-${SHORT_SHA} ${{ env.IMAGE }}:latest-dev

      - name: Push tags
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          docker push ${{ env.IMAGE }}:sha-${SHORT_SHA}
          docker push ${{ env.IMAGE }}:latest-dev

  deploy-dev:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          script: ${{ vars.SERVICE_NAME }}
